name: Elixir CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - 'master'
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: '23.2.3'
          elixir-version: '1.11.3'
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
        env:
          MIX_ENV: test
      - run: mix format --check-formatted --dry-run
      - run: mix credo --strict
        env:
          MIX_ENV: test
      - run: mix test
